# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broute.proto\x12\x05route\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x02\n\x05Route\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06origin\x18\x02 \x01(\x03\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\x03\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x10\n\x08\x63lientId\x18\x06 \x01(\x03\x12\x12\n\nclientPort\x18\x07 \x01(\x03\x12\x13\n\x0bprocessedBy\x18\x08 \x01(\x0c\x12\x17\n\x0f\x63lientMessageId\x18\t \x01(\x03\x12\x14\n\x0cserverOutput\x18\n \x01(\x0c\x12\x17\n\x0f\x63lientStartTime\x18\x0b \x01(\t\x12\x1d\n\x15inboundQueueEntryTime\x18\x0c \x01(\t\x12\x1c\n\x14inboundQueueExitTime\x18\r \x01(\t\x12\x1e\n\x16outboundQueueEntryTime\x18\x0e \x01(\t\x12\x1d\n\x15outboundQueueExitTime\x18\x0f \x01(\t\x12\x14\n\x0cisFromClient\x18\x10 \x01(\x08\x12\x10\n\x08lbPortNo\x18\x11 \x01(\x03\x32\x37\n\x0cRouteService\x12\'\n\x07request\x12\x0c.route.Route\x1a\x0c.route.Route\"\x00\x42\x04H\x01P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001P\001'
  _ROUTE._serialized_start=56
  _ROUTE._serialized_end=438
  _ROUTESERVICE._serialized_start=440
  _ROUTESERVICE._serialized_end=495
# @@protoc_insertion_point(module_scope)
